## Preprocessing

In [5]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

In [38]:
#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [39]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_df = application_df.drop(columns=["EIN", "NAME"])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [40]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [41]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE
ap_counts = application_df["APPLICATION_TYPE"].value_counts()
ap_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [42]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE

application_types_to_replace = []

for index, val in ap_counts.items():
    if val <= 100:
        application_types_to_replace.append(index)


# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: APPLICATION_TYPE, dtype: int64

In [43]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE
class_count = df["CLASSIFICATION"].value_counts()
class_count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [44]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
df["CLASSIFICATION"].value_counts().loc[lambda x : x>1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [45]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace = []
for index, val in class_count.items():
    if val <= 200:
        classifications_to_replace.append(index)
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1197
C7000      777
C1700      287
Name: CLASSIFICATION, dtype: int64

In [48]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
dum_df = pd.get_dummies(application_df)
dum_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [49]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
y = dum_df["IS_SUCCESSFUL"]
X = dum_df.drop("IS_SUCCESSFUL", axis=1)
# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1234)

In [50]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [62]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=5, activation="relu", input_dim=46))
# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=5, activation="relu"))
# Output layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))
# Check the structure of the model
nn.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_21 (Dense)            (None, 5)                 235

 dense_22 (Dense)            (None, 5)                 30

 dense_23 (Dense)            (None, 1)                 6

=================================================================
Total params: 271
Trainable params: 271
Non-trainable params: 0
_________________________________________________________________

In [63]:
# Compile the model
#  YOUR CODE GOES HERE
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [65]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn.fit(X_train_scaled, y_train, epochs=200)

Epoch 1/200
804/804 [==============================] - 1s 1ms/step - loss: 0.6206 - accuracy: 0.6803
Epoch 2/200
804/804 [==============================] - 1s 933us/step - loss: 0.5781 - accuracy: 0.71130s - loss: 0.5793 - accuracy: 0.71
Epoch 3/200
804/804 [==============================] - 1s 913us/step - loss: 0.5690 - accuracy: 0.7166
Epoch 4/200
804/804 [==============================] - 1s 947us/step - loss: 0.5664 - accuracy: 0.7191
Epoch 5/200
804/804 [==============================] - 1s 938us/step - loss: 0.5648 - accuracy: 0.7187
Epoch 6/200
804/804 [==============================] - 1s 936us/step - loss: 0.5638 - accuracy: 0.7194
Epoch 7/200
804/804 [==============================] - 1s 949us/step - loss: 0.5627 - accuracy: 0.7206
Epoch 8/200
804/804 [==============================] - 1s 969us/step - loss: 0.5614 - accuracy: 0.7207
Epoch 9/200
804/804 [==============================] - 1s 888us/step - loss: 0.5609 - accuracy: 0.7214
Epoch 10/200
804/804 [==============================] - 1s 933us/step - loss: 0.5603 - accuracy: 0.7217
Epoch 11/200
804/804 [==============================] - 1s 939us/step - loss: 0.5598 - accuracy: 0.7221
Epoch 12/200
804/804 [==============================] - 1s 937us/step - loss: 0.5596 - accuracy: 0.7209
Epoch 13/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5592 - accuracy: 0.7217
Epoch 14/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5589 - accuracy: 0.7217
Epoch 15/200
804/804 [==============================] - 1s 978us/step - loss: 0.5588 - accuracy: 0.7220
Epoch 16/200
804/804 [==============================] - 1s 920us/step - loss: 0.5583 - accuracy: 0.7221
Epoch 17/200
804/804 [==============================] - 1s 979us/step - loss: 0.5584 - accuracy: 0.7225
Epoch 18/200
804/804 [==============================] - 1s 971us/step - loss: 0.5581 - accuracy: 0.7241
Epoch 19/200
804/804 [==============================] - 1s 897us/step - loss: 0.5578 - accuracy: 0.7226
Epoch 20/200
804/804 [==============================] - 1s 880us/step - loss: 0.5563 - accuracy: 0.7226
Epoch 21/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5562 - accuracy: 0.7227
Epoch 22/200
804/804 [==============================] - 1s 986us/step - loss: 0.5560 - accuracy: 0.7230
Epoch 23/200
804/804 [==============================] - 1s 938us/step - loss: 0.5559 - accuracy: 0.7228
Epoch 24/200
804/804 [==============================] - 1s 982us/step - loss: 0.5557 - accuracy: 0.72280s - loss: 0.5555 - accura
Epoch 25/200
804/804 [==============================] - 1s 955us/step - loss: 0.5553 - accuracy: 0.7231
Epoch 26/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5552 - accuracy: 0.7226
Epoch 27/200
804/804 [==============================] - 1s 965us/step - loss: 0.5551 - accuracy: 0.7233
Epoch 28/200
804/804 [==============================] - 1s 962us/step - loss: 0.5550 - accuracy: 0.7226
Epoch 29/200
804/804 [==============================] - 1s 922us/step - loss: 0.5548 - accuracy: 0.7230
Epoch 30/200
804/804 [==============================] - 1s 975us/step - loss: 0.5547 - accuracy: 0.7228
Epoch 31/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5548 - accuracy: 0.7229
Epoch 32/200
804/804 [==============================] - 1s 924us/step - loss: 0.5543 - accuracy: 0.72320s - loss: 0.5555 - accu
Epoch 33/200
804/804 [==============================] - 1s 919us/step - loss: 0.5544 - accuracy: 0.7227
Epoch 34/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5542 - accuracy: 0.7235
Epoch 35/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5542 - accuracy: 0.7233
Epoch 36/200
804/804 [==============================] - 1s 881us/step - loss: 0.5542 - accuracy: 0.7231
Epoch 37/200
804/804 [==============================] - 1s 864us/step - loss: 0.5541 - accuracy: 0.72290s - loss: 0.550
Epoch 38/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5542 - accuracy: 0.7231
Epoch 39/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5539 - accuracy: 0.7231
Epoch 40/200
804/804 [==============================] - 1s 912us/step - loss: 0.5541 - accuracy: 0.7232
Epoch 41/200
804/804 [==============================] - 1s 930us/step - loss: 0.5536 - accuracy: 0.7241
Epoch 42/200
804/804 [==============================] - 1s 928us/step - loss: 0.5538 - accuracy: 0.7229
Epoch 43/200
804/804 [==============================] - 1s 928us/step - loss: 0.5538 - accuracy: 0.7240
Epoch 44/200
804/804 [==============================] - 1s 928us/step - loss: 0.5535 - accuracy: 0.7241
Epoch 45/200
804/804 [==============================] - 1s 941us/step - loss: 0.5538 - accuracy: 0.7241
Epoch 46/200
804/804 [==============================] - 1s 934us/step - loss: 0.5536 - accuracy: 0.7246
Epoch 47/200
804/804 [==============================] - 1s 944us/step - loss: 0.5532 - accuracy: 0.7241
Epoch 48/200
804/804 [==============================] - 1s 930us/step - loss: 0.5533 - accuracy: 0.7248
Epoch 49/200
804/804 [==============================] - 1s 902us/step - loss: 0.5534 - accuracy: 0.7247
Epoch 50/200
804/804 [==============================] - 1s 901us/step - loss: 0.5533 - accuracy: 0.7247
Epoch 51/200
804/804 [==============================] - 1s 943us/step - loss: 0.5530 - accuracy: 0.7245
Epoch 52/200
804/804 [==============================] - 1s 939us/step - loss: 0.5532 - accuracy: 0.7242
Epoch 53/200
804/804 [==============================] - 1s 937us/step - loss: 0.5530 - accuracy: 0.7243
Epoch 54/200
804/804 [==============================] - 1s 959us/step - loss: 0.5530 - accuracy: 0.7252
Epoch 55/200
804/804 [==============================] - 1s 963us/step - loss: 0.5522 - accuracy: 0.7252
Epoch 56/200
804/804 [==============================] - 1s 947us/step - loss: 0.5515 - accuracy: 0.7249
Epoch 57/200
804/804 [==============================] - 1s 940us/step - loss: 0.5514 - accuracy: 0.7248
Epoch 58/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5515 - accuracy: 0.7250
Epoch 59/200
804/804 [==============================] - 1s 878us/step - loss: 0.5513 - accuracy: 0.7250
Epoch 60/200
804/804 [==============================] - 1s 892us/step - loss: 0.5512 - accuracy: 0.7251
Epoch 61/200
804/804 [==============================] - 1s 908us/step - loss: 0.5511 - accuracy: 0.7235
Epoch 62/200
804/804 [==============================] - 1s 963us/step - loss: 0.5511 - accuracy: 0.7245
Epoch 63/200
804/804 [==============================] - 1s 899us/step - loss: 0.5512 - accuracy: 0.7245
Epoch 64/200
804/804 [==============================] - 1s 967us/step - loss: 0.5511 - accuracy: 0.7247
Epoch 65/200
804/804 [==============================] - 1s 929us/step - loss: 0.5513 - accuracy: 0.7254
Epoch 66/200
804/804 [==============================] - 1s 961us/step - loss: 0.5508 - accuracy: 0.7250
Epoch 67/200
804/804 [==============================] - 1s 896us/step - loss: 0.5510 - accuracy: 0.7249
Epoch 68/200
804/804 [==============================] - 1s 976us/step - loss: 0.5508 - accuracy: 0.7251
Epoch 69/200
804/804 [==============================] - 1s 889us/step - loss: 0.5510 - accuracy: 0.7255
Epoch 70/200
804/804 [==============================] - 1s 977us/step - loss: 0.5510 - accuracy: 0.7250
Epoch 71/200
804/804 [==============================] - 1s 926us/step - loss: 0.5509 - accuracy: 0.7252
Epoch 72/200
804/804 [==============================] - 1s 922us/step - loss: 0.5506 - accuracy: 0.7253
Epoch 73/200
804/804 [==============================] - 1s 929us/step - loss: 0.5510 - accuracy: 0.7254
Epoch 74/200
804/804 [==============================] - 1s 996us/step - loss: 0.5510 - accuracy: 0.7252
Epoch 75/200
804/804 [==============================] - 1s 945us/step - loss: 0.5509 - accuracy: 0.7247
Epoch 76/200
804/804 [==============================] - 1s 886us/step - loss: 0.5508 - accuracy: 0.7249
Epoch 77/200
804/804 [==============================] - 1s 907us/step - loss: 0.5508 - accuracy: 0.7256
Epoch 78/200
804/804 [==============================] - 1s 938us/step - loss: 0.5507 - accuracy: 0.7251
Epoch 79/200

804/804 [==============================] - 1s 933us/step - loss: 0.5506 - accuracy: 0.7250
Epoch 80/200
804/804 [==============================] - 1s 899us/step - loss: 0.5507 - accuracy: 0.7254
Epoch 81/200
804/804 [==============================] - 1s 901us/step - loss: 0.5507 - accuracy: 0.7251
Epoch 82/200
804/804 [==============================] - 1s 908us/step - loss: 0.5511 - accuracy: 0.7247
Epoch 83/200
804/804 [==============================] - 1s 925us/step - loss: 0.5509 - accuracy: 0.7251
Epoch 84/200
804/804 [==============================] - 1s 930us/step - loss: 0.5507 - accuracy: 0.7254
Epoch 85/200
804/804 [==============================] - 1s 912us/step - loss: 0.5508 - accuracy: 0.7250
Epoch 86/200
804/804 [==============================] - 1s 930us/step - loss: 0.5507 - accuracy: 0.7251
Epoch 87/200
804/804 [==============================] - 1s 950us/step - loss: 0.5509 - accuracy: 0.7255
Epoch 88/200
804/804 [==============================] - 1s 936us/step - loss: 0.5506 - accuracy: 0.7249
Epoch 89/200
804/804 [==============================] - 1s 934us/step - loss: 0.5504 - accuracy: 0.7252
Epoch 90/200
804/804 [==============================] - 1s 959us/step - loss: 0.5506 - accuracy: 0.7246
Epoch 91/200
804/804 [==============================] - 1s 957us/step - loss: 0.5505 - accuracy: 0.7252
Epoch 92/200
804/804 [==============================] - 1s 981us/step - loss: 0.5506 - accuracy: 0.7249
Epoch 93/200
804/804 [==============================] - 1s 923us/step - loss: 0.5507 - accuracy: 0.7255
Epoch 94/200
804/804 [==============================] - 1s 943us/step - loss: 0.5506 - accuracy: 0.7254
Epoch 95/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5507 - accuracy: 0.7255
Epoch 96/200
804/804 [==============================] - 1s 976us/step - loss: 0.5505 - accuracy: 0.7254
Epoch 97/200
804/804 [==============================] - 1s 940us/step - loss: 0.5506 - accuracy: 0.7252
Epoch 98/200
804/804 [==============================] - 1s 957us/step - loss: 0.5505 - accuracy: 0.7255
Epoch 99/200
804/804 [==============================] - 1s 949us/step - loss: 0.5505 - accuracy: 0.7254
Epoch 100/200
804/804 [==============================] - 1s 957us/step - loss: 0.5507 - accuracy: 0.7248
Epoch 101/200
804/804 [==============================] - 1s 964us/step - loss: 0.5506 - accuracy: 0.7253
Epoch 102/200
804/804 [==============================] - 1s 945us/step - loss: 0.5506 - accuracy: 0.7249
Epoch 103/200
804/804 [==============================] - 1s 943us/step - loss: 0.5505 - accuracy: 0.7251
Epoch 104/200
804/804 [==============================] - 1s 932us/step - loss: 0.5503 - accuracy: 0.7254
Epoch 105/200
804/804 [==============================] - 1s 960us/step - loss: 0.5505 - accuracy: 0.7253
Epoch 106/200
804/804 [==============================] - 1s 940us/step - loss: 0.5505 - accuracy: 0.7253
Epoch 107/200
804/804 [==============================] - 1s 990us/step - loss: 0.5503 - accuracy: 0.7259
Epoch 108/200
804/804 [==============================] - 1s 913us/step - loss: 0.5503 - accuracy: 0.7245
Epoch 109/200
804/804 [==============================] - 1s 969us/step - loss: 0.5501 - accuracy: 0.7252
Epoch 110/200
804/804 [==============================] - 1s 933us/step - loss: 0.5501 - accuracy: 0.7258
Epoch 111/200
804/804 [==============================] - 1s 931us/step - loss: 0.5501 - accuracy: 0.7254
Epoch 112/200
804/804 [==============================] - 1s 952us/step - loss: 0.5497 - accuracy: 0.7255
Epoch 113/200
804/804 [==============================] - 1s 966us/step - loss: 0.5500 - accuracy: 0.7254
Epoch 114/200
804/804 [==============================] - 1s 928us/step - loss: 0.5498 - accuracy: 0.72510s - loss: 0.5522 - accu
Epoch 115/200
804/804 [==============================] - 1s 968us/step - loss: 0.5499 - accuracy: 0.7255
Epoch 116/200
804/804 [==============================] - 1s 948us/step - loss: 0.5498 - accuracy: 0.7257
Epoch 117/200
804/804 [==============================] - 1s 925us/step - loss: 0.5497 - accuracy: 0.7266
Epoch 118/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5498 - accuracy: 0.7251
Epoch 119/200
804/804 [==============================] - 1s 999us/step - loss: 0.5500 - accuracy: 0.7261
Epoch 120/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5497 - accuracy: 0.7259
Epoch 121/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5497 - accuracy: 0.7262
Epoch 122/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5497 - accuracy: 0.7259
Epoch 123/200
804/804 [==============================] - 1s 881us/step - loss: 0.5500 - accuracy: 0.7263
Epoch 124/200
804/804 [==============================] - 1s 913us/step - loss: 0.5500 - accuracy: 0.7257
Epoch 125/200
804/804 [==============================] - 1s 946us/step - loss: 0.5498 - accuracy: 0.7274
Epoch 126/200
804/804 [==============================] - 1s 902us/step - loss: 0.5495 - accuracy: 0.7283
Epoch 127/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5493 - accuracy: 0.7285
Epoch 128/200
804/804 [==============================] - 1s 898us/step - loss: 0.5494 - accuracy: 0.7287
Epoch 129/200
804/804 [==============================] - 1s 928us/step - loss: 0.5494 - accuracy: 0.7285
Epoch 130/200
804/804 [==============================] - 1s 923us/step - loss: 0.5489 - accuracy: 0.72850s - loss:
Epoch 131/200
804/804 [==============================] - 1s 967us/step - loss: 0.5490 - accuracy: 0.7287
Epoch 132/200
804/804 [==============================] - 1s 947us/step - loss: 0.5491 - accuracy: 0.7282
Epoch 133/200
804/804 [==============================] - 1s 923us/step - loss: 0.5491 - accuracy: 0.7290
Epoch 134/200
804/804 [==============================] - 1s 906us/step - loss: 0.5491 - accuracy: 0.7288
Epoch 135/200
804/804 [==============================] - 1s 936us/step - loss: 0.5492 - accuracy: 0.7282
Epoch 136/200
804/804 [==============================] - 1s 963us/step - loss: 0.5491 - accuracy: 0.7278
Epoch 137/200
804/804 [==============================] - 1s 957us/step - loss: 0.5492 - accuracy: 0.7284
Epoch 138/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5492 - accuracy: 0.7279
Epoch 139/200
804/804 [==============================] - 1s 899us/step - loss: 0.5491 - accuracy: 0.7284
Epoch 140/200
804/804 [==============================] - 1s 934us/step - loss: 0.5489 - accuracy: 0.7279
Epoch 141/200
804/804 [==============================] - 1s 925us/step - loss: 0.5490 - accuracy: 0.7282
Epoch 142/200
804/804 [==============================] - 1s 913us/step - loss: 0.5490 - accuracy: 0.7284
Epoch 143/200
804/804 [==============================] - 1s 943us/step - loss: 0.5491 - accuracy: 0.7285
Epoch 144/200
804/804 [==============================] - 1s 956us/step - loss: 0.5491 - accuracy: 0.7286
Epoch 145/200
804/804 [==============================] - 1s 889us/step - loss: 0.5490 - accuracy: 0.7284
Epoch 146/200
804/804 [==============================] - 1s 980us/step - loss: 0.5490 - accuracy: 0.7285
Epoch 147/200
804/804 [==============================] - 1s 932us/step - loss: 0.5490 - accuracy: 0.7287
Epoch 148/200
804/804 [==============================] - 1s 994us/step - loss: 0.5491 - accuracy: 0.7294
Epoch 149/200
804/804 [==============================] - 1s 966us/step - loss: 0.5489 - accuracy: 0.7288
Epoch 150/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5488 - accuracy: 0.7290
Epoch 151/200
804/804 [==============================] - 1s 932us/step - loss: 0.5488 - accuracy: 0.7280
Epoch 152/200
804/804 [==============================] - 1s 950us/step - loss: 0.5489 - accuracy: 0.7285
Epoch 153/200
804/804 [==============================] - 1s 973us/step - loss: 0.5490 - accuracy: 0.7285
Epoch 154/200
804/804 [==============================] - 1s 959us/step - loss: 0.5490 - accuracy: 0.7284
Epoch 155/200
804/804 [==============================] - 1s 953us/step - loss: 0.5487 - accuracy: 0.7282
Epoch 156/200
804/804 [==============================] - 1s 999us/step - loss: 0.5488 - accuracy: 0.7283
Epoch 157/200

804/804 [==============================] - 1s 992us/step - loss: 0.5487 - accuracy: 0.7286
Epoch 158/200
804/804 [==============================] - 1s 901us/step - loss: 0.5488 - accuracy: 0.7281
Epoch 159/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5487 - accuracy: 0.7283
Epoch 160/200
804/804 [==============================] - 1s 957us/step - loss: 0.5487 - accuracy: 0.7289
Epoch 161/200
804/804 [==============================] - 1s 872us/step - loss: 0.5487 - accuracy: 0.7284
Epoch 162/200
804/804 [==============================] - 1s 947us/step - loss: 0.5485 - accuracy: 0.7289
Epoch 163/200
804/804 [==============================] - 1s 954us/step - loss: 0.5489 - accuracy: 0.7282
Epoch 164/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5487 - accuracy: 0.7285
Epoch 165/200
804/804 [==============================] - 1s 929us/step - loss: 0.5488 - accuracy: 0.7273
Epoch 166/200
804/804 [==============================] - 1s 932us/step - loss: 0.5497 - accuracy: 0.7258
Epoch 167/200
804/804 [==============================] - 1s 912us/step - loss: 0.5489 - accuracy: 0.7282
Epoch 168/200
804/804 [==============================] - 1s 924us/step - loss: 0.5488 - accuracy: 0.7278
Epoch 169/200
804/804 [==============================] - 1s 985us/step - loss: 0.5487 - accuracy: 0.7289
Epoch 170/200
804/804 [==============================] - 1s 969us/step - loss: 0.5489 - accuracy: 0.7291
Epoch 171/200
804/804 [==============================] - 1s 920us/step - loss: 0.5486 - accuracy: 0.7286
Epoch 172/200
804/804 [==============================] - 1s 919us/step - loss: 0.5488 - accuracy: 0.7290
Epoch 173/200
804/804 [==============================] - 1s 903us/step - loss: 0.5486 - accuracy: 0.7289
Epoch 174/200
804/804 [==============================] - 1s 929us/step - loss: 0.5485 - accuracy: 0.7288
Epoch 175/200
804/804 [==============================] - 1s 953us/step - loss: 0.5486 - accuracy: 0.72860s - loss: 0.5499 - accuracy:
Epoch 176/200
804/804 [==============================] - 1s 964us/step - loss: 0.5484 - accuracy: 0.72850s - loss: 0.5490 -
Epoch 177/200
804/804 [==============================] - 1s 977us/step - loss: 0.5484 - accuracy: 0.7280
Epoch 178/200
804/804 [==============================] - 1s 944us/step - loss: 0.5485 - accuracy: 0.7283
Epoch 179/200
804/804 [==============================] - 1s 989us/step - loss: 0.5487 - accuracy: 0.7285
Epoch 180/200
804/804 [==============================] - 1s 992us/step - loss: 0.5485 - accuracy: 0.7287
Epoch 181/200
804/804 [==============================] - 1s 978us/step - loss: 0.5487 - accuracy: 0.7284
Epoch 182/200
804/804 [==============================] - 1s 971us/step - loss: 0.5484 - accuracy: 0.7291
Epoch 183/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5484 - accuracy: 0.7289: 0s - loss: 0.5473 - accuracy: 0.
Epoch 184/200
804/804 [==============================] - 1s 974us/step - loss: 0.5483 - accuracy: 0.7293
Epoch 185/200
804/804 [==============================] - 1s 975us/step - loss: 0.5483 - accuracy: 0.7289
Epoch 186/200
804/804 [==============================] - 1s 970us/step - loss: 0.5483 - accuracy: 0.7292
Epoch 187/200
804/804 [==============================] - 1s 986us/step - loss: 0.5485 - accuracy: 0.7289
Epoch 188/200
804/804 [==============================] - 1s 985us/step - loss: 0.5484 - accuracy: 0.7289
Epoch 189/200
804/804 [==============================] - 1s 968us/step - loss: 0.5484 - accuracy: 0.7295
Epoch 190/200
804/804 [==============================] - 1s 945us/step - loss: 0.5483 - accuracy: 0.7297
Epoch 191/200
804/804 [==============================] - 1s 972us/step - loss: 0.5484 - accuracy: 0.7294
Epoch 192/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5485 - accuracy: 0.7292
Epoch 193/200
804/804 [==============================] - 1s 928us/step - loss: 0.5483 - accuracy: 0.72900s - loss: 0.543
Epoch 194/200
804/804 [==============================] - 1s 933us/step - loss: 0.5485 - accuracy: 0.72940s - loss: 0
Epoch 195/200
804/804 [==============================] - 1s 996us/step - loss: 0.5484 - accuracy: 0.7298
Epoch 196/200
804/804 [==============================] - 1s 930us/step - loss: 0.5484 - accuracy: 0.7295
Epoch 197/200
804/804 [==============================] - 1s 968us/step - loss: 0.5482 - accuracy: 0.7297
Epoch 198/200
804/804 [==============================] - 1s 934us/step - loss: 0.5484 - accuracy: 0.7297
Epoch 199/200
804/804 [==============================] - 1s 937us/step - loss: 0.5484 - accuracy: 0.7295
Epoch 200/200
804/804 [==============================] - 1s 935us/step - loss: 0.5485 - accuracy: 0.7303

In [68]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5516 - accuracy: 0.7300 - 176ms/epoch - 658us/step
Loss: 0.551574170589447, Accuracy: 0.7300291657447815

In [69]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
nn.save("nn.h5")